// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbezfdzfwbzsiyuujcxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiZXpmZHpmd2J6c2l5dXVqY3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTU2NjAsImV4cCI6MjA2NTYzMTY2MH0.U2gSTua_QBKPRTQUfJNNRqPWJOuuJLcuOvxCFLf6F_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);